kind: Pod
apiVersion: v1
metadata:
  name: expense
  labels:
    name: expense
spec:
  containers:
  - name: nginx
    image: nginx
  - name: alma
    image: "almalinux:9"
    command: ["sleep", "20000"]
