kind: Deployment
apiVersion: apps/v1
metadata:
  name: suri-nginx
  labels:
    app: suri-nginx
    purpose: deployment
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suri-nginx
      tier: web
      project: test
  template:
    metadata:
      labels:
        app: suri-nginx
        tier: web
        project: test
        extra-key: extra-value
    spec:
      containers:
      - name: suri-nginx
        image: nginx

