apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: project
                operator: In
                values:
                - expense
          weight: 1  # Weight of the preference. Higher weight means stronger preference.
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  containers:
  - name: nginx-node-affinity
    image: nginx
